name: ncqp-streamlit
channels:
  - conda-forge
dependencies:
  # CondaにはSCIPとpip本体だけをインストールさせる
  - scip
  - pip
  - pip:
      # 残りのPythonパッケージは高速なpipに任せる
      - streamlit
      - pyomo
      - pandas
      - matplotlib
